theme: minima
title: HAMZA MUHAMMAD GAME DEVELOPER PORTFOLIO
author: HAMZA MUHAMMAD
email: hamzamuhammad2010@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hamza Muhamamd Game Developer Portfolio Website!

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
